' Yyg Custom PlantUML Configs and Shortcuts
' - This defines color variables for use in various plantuml diagrams, providing a more consistent style among my graphics.
'  https://github.com/theyyg/yyg-nix-config/tree/master/plantuml
'  patterned after the plant uml standard library https://plantuml.com/stdlib
'
' Download and install plantuml https://plantuml.com/download
' Install plantuml-mode via melpa
'
' To use in org mode:
'  First: Run these scripts in a scratch buffer or add to emacs config
'   Scratch:
'    (setq org-plantuml-jar-path (expand-file-name "/home/you/path/to/plantuml.jar"))
'    (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
'    (org-babel-do-load-languages 'org-babel-load-languages '((plantuml . t)))
'
'   .emacs.el:
'    (setq org-plantuml-jar-path (expand-file-name "/home/you/path/to/plantuml.jar"))
'
'    (org-babel-do-load-languages
'     'org-babel-load-languages
'     '((plantuml . t)))
'
'    (defun init-plantuml()
'      (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
'      (org-babel-do-load-languages 'org-babel-load-languages '((plantuml . t)))
'      )
'
'    (add-hook 'org-mode-hook 'init-plantuml)
'
' Using PlantUML in org-mode
'  Create a plantuml source block:
'   #+begin_src plantuml :file ./chart-name.png
'   title Chart Title
'
'
'   #+end_src
'
'  Add the following line at the top of the org file to prevent evaluation prompts:
'  # -*- org-confirm-babel-evaluate: nil; -*-
'
' or add this sections to the bottom of the org file:
'
' * Local Variables :noexport:
' Local Variables:
' org-confirm-babel-evaluate: nil
' End:

'
'  Publish plant-uml in org doc by executing C-c C-e h o

' ================================
' Define Colors
'

' Border Outline
!$clrBorderLt = "989898"
!$clrBorder = "686868"
!$clrBorderDk = "101010"

' Text
!$clrTextLt = "FFFFFF"
!$clrText = "000000"
!$clrTextDk = "000000"

' Pink
!$clrPinkLt = "FF80CA"
!$clrPink = "CC338C"
!$clrPinkDk = "8E0B6D"
' Red
!$clrRedLt = "FF8580"
!$clrRed = "CC3933"
!$clrRedDk = "8E0B0B"
' Orange
!$clrOrangeLt = "FFAF80"
!$clrOrange = "CC6C33"
!$clrOrangeDk = "8E310B"
' Yellow
!$clrYellowLt = "FFDA80"
!$clrYellow = "CC9F33"
!$clrYellowDk = "8E680B"
' Grass
!$clrGrassLt = "EFFF80"
!$clrGrass = "B9CC33"
!$clrGrassDk = "5D8E0B"
' Green
!$clrGreenLt = "80FF8F"
!$clrGreen = "33CC46"
!$clrGreenDk = "0B8E3C"
' Blue
!$clrBlueLt = "80EFFF"
!$clrBlue = "33B9CC"
!$clrBlueDk = "0B5D8E"
' Indigo
!$clrIndigoLt = "8A80FF"
!$clrIndigo = "4033CC"
!$clrIndigoDk = "160B8E"
' Purple
!$clrPurpleLt = "DF80FF"
!$clrPurple = "A633CC"
!$clrPurpleDk = "570B8E"
' Grey
!$clrWhite = "FFFFFF"
!$clrGreyLt = "BFBFBF"
!$clrGrey = "808080"
!$clrGreyDk = "4C4C4C"
!$clrBlack = "000000"

' Categories
!$clrCloud = "$clrPink"
!$clrLocal = "$clrRed"
!$clrApp = "$clrOrange"
!$clrPlugin = "$clrYellow"
!$clrService = "$clrGreen"
!$clrEngine = "$clrBlue"
!$clrSystem = "$clrIndigo"
!$clrDevice = "$clrPurple"
!$clrBg = "$clrGrey"
!$clrClear = "transparent"

!$aud = "33F,bold"
!$audref = "33F,dashed"
!$ctl = "000,bold"
!$ctlref = "000,dashed"
!$hid = "hidden"

' ================================
' get_color Function
'
!function get_color($color="$clrBg", $shade="none")
!log get_color{$color,$shade}

!if (%substr($color,0,1) == "#")
!if ($shade == "light")
!$fullColor = %lighten($color, 50)
!elseif ($shade == "none")
!$fullColor = $color
!elseif ($shade == "dark")
!$fullColor = %darken($color, 50)
!endif
!log fullColor: $fullColor
!$fullColor = %substr($fullColor,1,6)
!log fullColor: $fullColor

!else
!$tempColor = $color
!while (%substr($tempColor,0,4) == "$clr")
!$color = $tempColor
!$tempColor = %get_variable_value($color)
!log tempColor: $tempColor color: $color
!endwhile

!if ($shade == "light")
!$fullColor = %get_variable_value($color + "Lt")
!elseif ($shade == "dark")
!$fullColor = %get_variable_value($color + "Dk")
!else
!$fullColor = %get_variable_value($color)
!endif

!endif

!log color: $fullColor
!return $fullColor
!endfunction

' ================================
' flip_shade Function
'
!function flip_shade($shade="none")

!if ($shade == "light")
!$flipped_shade = "dark"
!else
!$flipped_shade = "light"
!endif

!return $flipped_shade
!endfunction