' Yyg Custom PlantUML Configs and Shortcuts
' - This uses the plantuml "use case" style
'  https://github.com/theyyg/yyg-nix-config/tree/master/plantuml
'  patterned after the plant uml standard library https://plantuml.com/stdlib
'
' Download and install plantuml https://plantuml.com/download
' Install plantuml-mode via melpa
'
' To use in org mode:
'  First: Run these scripts in a scratch buffer or add to emacs config
'   Scratch:
'    (setq org-plantuml-jar-path (expand-file-name "/home/you/path/to/plantuml.jar"))
'    (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
'    (org-babel-do-load-languages 'org-babel-load-languages '((plantuml . t)))
'
'   .emacs.el:
'    (setq org-plantuml-jar-path (expand-file-name "/home/you/path/to/plantuml.jar"))
'
'    (org-babel-do-load-languages
'     'org-babel-load-languages
'     '((plantuml . t)))
'
'    (defun init-plantuml()
'      (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
'      (org-babel-do-load-languages 'org-babel-load-languages '((plantuml . t)))
'      )
'
'    (add-hook 'org-mode-hook 'init-plantuml)
'
' Using PlantUML in org-mode
'  Create a plantuml source block:
'   #+begin_src plantuml :file ./chart-name.png
'   title Chart Title
'
'
'   #+end_src
'
'  Add the following line at the top of the org file to prevent evaluation prompts:
'  # -*- org-confirm-babel-evaluate: nil; -*-
'
' or add this sections to the bottom of the org file:
'
' * Local Variables :noexport:
' Local Variables:
' org-confirm-babel-evaluate: nil
' End:
'
'  Publish plant-uml in org doc by executing C-c C-e h o
'
' The following file is PlanUML preprocessor code to simplify consistent diagrams


' ===================================================
' LOOK INTO EBNF ELEMENTS FOR SIGNAL FLOW DIAGRAMS
' ===================================================

!include yyg-colors.puml

' ================================
' Factory Function
'
!procedure Factory($style, $alias, $label="none", $color="clrBg", $shade="none", $ref="false")
!log Factory{$style,$alias,$label,$color,$shade,$ref)
!$cmd = $style + " "

!if ($label != "none")
!$cmd = $cmd + '"' + $label + '"' + " as " + $alias
!else
!$cmd = $cmd + '"' + $alias + '"' + " "
!endif

!$textColor = %get_variable_value("$clrText")

!if ($color != "transparent")
!$fullColor = get_color($color, $shade)
!$textColor = get_color("$clrText", flip_shade($shade))
!$cmd = $cmd + " #" + $fullColor + ";line:" + $textColor
!endif

!if ($ref != "false")
!$cmd = $cmd + ";line.dashed"
!endif

!$cmd = $cmd + ";text:" + $textColor

!log $cmd
$cmd
!endprocedure

' ================================
' Block
'
!unquoted procedure Block($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(rectangle, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Round (Ellipse)
'
!unquoted procedure Round($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(storage, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Hex (Hexagon)
'
!unquoted procedure Hex($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(hexagon, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Ref (Reference)
'
'
!unquoted procedure Ref($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(rectangle, $alias, $label, $bg, "true", "none")
!endprocedure

' ================================
' System
'
'
!unquoted procedure System($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(package, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Box (Black Box)
'
'
!unquoted procedure Box($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(node, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Object
'
'
!unquoted procedure Object($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(card, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Cloud
'
!unquoted procedure Cloud($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(cloud, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Data
'
!unquoted procedure Data($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(usecase, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' DB - Database Container
'
!unquoted procedure Db($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(database, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Note (File)
'
'
!unquoted procedure Note($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(file, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Dir (Folder)
'
'
!unquoted procedure Dir($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(folder, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' List (Buff)
'
'
!unquoted procedure List($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(collections, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Frame
'
'
!unquoted procedure Frame($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(frame, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Algo (Algorithm)
'
'
!unquoted procedure Algo($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(action, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Buff (Double Buffer)
'
'
!unquoted procedure Buff($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(queue, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Plugin
'
'
!unquoted procedure Plugin($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(component, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' User
'
'
!unquoted procedure User($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(person, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Tool
'
'
!unquoted procedure Tool($alias, $label="none", $bg=$clrBg, $shade="none")
Factory(process, $alias, $label, $bg, $shade)
!endprocedure

' ================================
' Wrap
'
!unquoted procedure Pack($alias, $label="none", $bg=$bg, $shade="light")
Factory(package, $alias, $label, $bg, $shade)
!endprocedure

' Clear Wrap
!unquoted procedure Wrap($alias, $label="none")
Factory(package, $alias, $label, transparent)
!endprocedure

' ================================
' Layout Style
'
!$LAYOUT_TOP_DOWN = "top to bottom direction"
!$LAYOUT_LEFT_RIGHT = "left to right direction"

$LAYOUT_TOP_DOWN
'$LAYOUT_LEFT_RIGHT

skinparam line {
  'type polyline
  type ortho
}

skinparam ranksep 50
skinparam nodesep 50  

' ================================
' Package Style
'
skinparam package {
  Style Rectangle
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false
  RoundCorner 25

  BackgroundColor<<App>> $bgLt
  BackgroundColor<<Plugin>> $bgPluginLt
  BackgroundColor<<Service>> $bgServiceLt
  BackgroundColor<<Cloud>> $bgCloudLt

  ArrowColor black

  sep 10
}

' ================================
' Rectangle Style
'
skinparam rectangle {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false
  RoundCorner 15

  ArrowColor black
}

' ================================
' Storage Style
'
skinparam storage {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Usecase Style
'
skinparam usecase {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Hexagon Style
'
skinparam hexagon {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Node Style
'
skinparam node {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}


' ================================
' Card Style
'
skinparam card {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' File Style
'
skinparam file {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Folder Style
'
skinparam folder {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Queue Style
'
skinparam queue {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Person Style
'
skinparam person {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Actor Style
'
skinparam actor {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Database Style
'
skinparam Database {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Cloud Style
'
skinparam cloud {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Collections Style
'
skinparam collections {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Component Style
'
skinparam component {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Package Style
'
skinparam package {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

' ================================
' Frame Style
'
skinparam frame {
  BackgroundColor transparent
  FontColor $fontLt
  BorderColor $borderDk
  BorderThickness 1
  shadowing false

  ArrowColor black
}

skinparam arrow {
}

